{% set version = '0.9-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-misc3d
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/misc3d_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/misc3d/misc3d_{{ version }}.tar.gz
  sha256: a1e9291d625bd1312bae5b0e26d48b9362f66a8a0fabbf48891ba1d2432e4e82

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('misc3d')"           # [not win]
    - "\"%R%\" -e \"library('misc3d')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=misc3d
  license: GPL-3
  summary: A collection of miscellaneous 3d plots, including isosurfaces.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - FernandezMathieu

# Package: misc3d
# Title: Miscellaneous 3D Plots
# Version: 0.9-0
# Author: Dai Feng and Luke Tierney
# Maintainer: Luke Tierney <luke-tierney@uiowa.edu>
# Suggests: rgl, tkrplot, MASS
# Imports: grDevices, graphics, stats, tcltk
# Description: A collection of miscellaneous 3d plots, including isosurfaces.
# License: GPL
# NeedsCompilation: no
# Packaged: 2020-09-05 22:23:07 UTC; luke
# Repository: CRAN
# Date/Publication: 2020-09-06 04:50:06 UTC
