{% set name = "polyglot" %}
{% set version = "16.7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyglot-{{ version }}.tar.gz
  sha256: f7d9cca9a212622548e9416fb89f1238b994b8860ef49e03b7c82c67f9b6269b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - wheel >=0.23.0
    - PyICU >=1.8
    - cld2-cffi
    - six >=1.7.3
    - futures >=2.1.6
    - morfessor >=2.0.2a1
    - numpy >=1.6.1


test:
  imports:
    - polyglot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aboSamoor/polyglot
  summary: Polyglot is a natural language pipeline that supports massive multilingual applications.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
